module.exports = {
  appName: 'js13k-2018',
  sourceFiles: [
    "js/engine/core/setup.js",
    "js/engine/core/input.js",
    "js/engine/core/math.js",
    "js/engine/core/vector.js",
    "js/engine/core/rectangle.js",
    "js/engine/core/camera.js",
    "js/engine/core/scene.js",
    "js/engine/core/group.js",
    "js/engine/core/sprite.js",
    "js/engine/core/animator.js",
    "js/engine/core/collision.js",
    "js/engine/core/text_renderer.js",
    "js/engine/core/ui_button.js",
    "js/engine/core/scene_manager.js",
    "js/engine/core/events.js",
    "js/engine/core/init.js",

    "js/scenes/base.js",
    "js/scenes/menu.js",
    "js/scenes/connect.js",
    "js/scenes/filling.js",
    "js/scenes/calibrate.js",
    "js/scenes/seal.js",
    "js/scenes/tighten.js",
    "js/scenes/terminal.js",
    "js/scenes/auxiliary.js",
    "js/scenes/recharge.js",
    "js/scenes/recording.js",
    "js/scenes/ending.js",
    "js/scenes/level_selection.js",
    "js/aeros.js",
    "js/gauge.js",
    "js/main.js",
  ]
}
